nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ['http://localhost:4200']
    allow_headers: ['Content-Type', 'Authorization', 'Accept', 'X-Requested-With']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
    max_age: 3600
  paths:
    '^/api/':
      origin_regex: false
      allow_origin: ['http://localhost:4200']
      allow_headers: ['Content-Type', 'Authorization', 'Accept', 'X-Requested-With']
      allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
      max_age: 3600